#!/bin/bash
# While loop

echo "Ingrese el numero de veces que necesita repetir"
read VAL
COUNT=1

while [ $COUNT -le $VAL ]
do
echo "El numero de repeticiones es: $COUNT"
COUNT="`expr $COUNT + 1`"
done
